# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 18:50
from __future__ import unicode_literals

import cricket.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattingParScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bat_position', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('season', models.IntegerField(default=cricket.models.get_current_year)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('pc_slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('competition_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Inning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bat_team_id', models.CharField(max_length=8)),
                ('bowl_team_id', models.CharField(max_length=8)),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('overs', models.FloatField()),
                ('declared', models.BooleanField()),
                ('extras_byes', models.IntegerField(default=0)),
                ('extras_leg_byes', models.IntegerField(default=0)),
                ('extras_wides', models.IntegerField(default=0)),
                ('extras_no_balls', models.IntegerField(default=0)),
                ('extras_penalties', models.IntegerField(default=0)),
                ('extras_total', models.IntegerField(default=0)),
                ('highlights', models.TextField(default='')),
                ('complete_innings', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('last_updated', models.DateField()),
                ('competition_name', models.CharField(max_length=255)),
                ('competition_id', models.CharField(max_length=8)),
                ('competition_type', models.CharField(max_length=32)),
                ('match_type', models.CharField(max_length=64)),
                ('game_type', models.CharField(max_length=32)),
                ('match_id', models.CharField(max_length=8, unique=True)),
                ('match_date', models.DateField()),
                ('season', models.CharField(default=cricket.models.get_current_year, max_length=4)),
                ('ground_name', models.CharField(max_length=255)),
                ('ground_id', models.CharField(max_length=8)),
                ('home_team_name', models.CharField(max_length=255)),
                ('home_team_id', models.CharField(max_length=8)),
                ('home_club_name', models.CharField(max_length=255)),
                ('home_club_id', models.CharField(max_length=8)),
                ('away_team_name', models.CharField(max_length=255)),
                ('away_team_id', models.CharField(max_length=8)),
                ('away_club_name', models.CharField(max_length=255)),
                ('away_club_id', models.CharField(max_length=8)),
                ('umpire_1_id', models.CharField(default='', max_length=8)),
                ('umpire_1_name', models.CharField(default='', max_length=255)),
                ('umpire_2_id', models.CharField(default='', max_length=8)),
                ('umpire_2_name', models.CharField(default='', max_length=255)),
                ('toss_won_by_team_id', models.CharField(max_length=8)),
                ('toss', models.CharField(max_length=512)),
                ('batted_first', models.CharField(max_length=8)),
                ('result', models.CharField(max_length=2)),
                ('result_description', models.CharField(max_length=512)),
                ('result_applied_to', models.CharField(max_length=8)),
                ('match_notes', models.TextField()),
                ('number_of_players', models.IntegerField(default=0)),
                ('full_scorecard', models.BooleanField(default=False)),
                ('processing_issue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PCTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_id', models.CharField(max_length=8)),
                ('name', models.CharField(default='unsure', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.BooleanField(default=False)),
                ('wicket_keeper', models.BooleanField(default=False)),
                ('bat', models.BooleanField(default=False)),
                ('bat_position', models.IntegerField(default=0)),
                ('bat_runs', models.IntegerField(default=0)),
                ('bat_par_score', models.IntegerField(default=0)),
                ('bat_balls', models.IntegerField(default=0)),
                ('bat_how_out', models.CharField(default='DNB', max_length=32)),
                ('bat_inning_no', models.IntegerField(default=0)),
                ('bowl', models.BooleanField(default=False)),
                ('bowl_overs', models.FloatField(default=0)),
                ('bowl_runs', models.IntegerField(default=0)),
                ('bowl_maidens', models.IntegerField(default=0)),
                ('bowl_position', models.IntegerField(default=0)),
                ('bowl_pareconomy', models.FloatField(default=0.0)),
                ('bowl_wickets_lbw', models.IntegerField(default=0)),
                ('bowl_wickets_bowled', models.IntegerField(default=0)),
                ('bowl_wickets_stumped', models.IntegerField(default=0)),
                ('bowl_wickets_caught', models.IntegerField(default=0)),
                ('bowl_wickets_hit_wicket', models.IntegerField(default=0)),
                ('bowl_wickets_total', models.IntegerField(default=0)),
                ('bowl_inning_no', models.IntegerField(default=0)),
                ('field_catches', models.IntegerField(default=0)),
                ('field_run_outs', models.IntegerField(default=0)),
                ('field_stumped', models.IntegerField(default=0)),
                ('mvp', models.BooleanField(default=False)),
                ('mvp_total', models.FloatField(default=0.0)),
                ('mvp_bat_runs', models.FloatField(default=0.0)),
                ('mvp_bat_parscorebonus', models.FloatField(default=0.0)),
                ('mvp_bowl_assisted', models.FloatField(default=0.0)),
                ('mvp_bowl_unassisted', models.FloatField(default=0.0)),
                ('mvp_bowl_economybonus', models.FloatField(default=0.0)),
                ('mvp_field_assisted', models.FloatField(default=0.0)),
                ('mvp_field_unassisted', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayCricketTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=8)),
                ('team_name', models.CharField(max_length=64)),
                ('first_season', models.CharField(max_length=4)),
                ('fantasy_league', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('match_results', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('player_id', models.CharField(max_length=8)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Club')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=cricket.models.get_current_year)),
                ('value', models.FloatField(default=0)),
                ('classification', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_playervalue_player', to='cricket.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='Choose your team name', max_length=255)),
                ('season', models.IntegerField(default=cricket.models.get_current_year)),
                ('penalties', models.IntegerField(default=0)),
                ('stripe_payment_token', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_team_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.BooleanField(default=False)),
                ('date_active', models.DateField(default=django.utils.timezone.now)),
                ('date_deactive', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_teamplayer_player', to='cricket.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_teamplayer_team', to='cricket.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Umpire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_id', models.CharField(max_length=31)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UmpireAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Match')),
                ('umpire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Umpire')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='bat_out_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bat_bowler', to='cricket.Player'),
        ),
        migrations.AddField(
            model_name='performance',
            name='bat_out_fielder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bat_fielder', to='cricket.Player'),
        ),
        migrations.AddField(
            model_name='performance',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Match'),
        ),
        migrations.AddField(
            model_name='performance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='fk_away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='cricket.PCTeam'),
        ),
        migrations.AddField(
            model_name='match',
            name='fk_competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Competition'),
        ),
        migrations.AddField(
            model_name='match',
            name='fk_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.MatchDate'),
        ),
        migrations.AddField(
            model_name='match',
            name='fk_ground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Ground'),
        ),
        migrations.AddField(
            model_name='match',
            name='fk_home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='cricket.PCTeam'),
        ),
        migrations.AddField(
            model_name='match',
            name='fk_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.PlayCricketTeam'),
        ),
        migrations.AddField(
            model_name='inning',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Match'),
        ),
    ]
