# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bat', models.BooleanField(default=False)),
                ('bat_position', models.IntegerField(default=0)),
                ('bat_runs', models.IntegerField(default=0)),
                ('bat_par_score', models.IntegerField(default=0)),
                ('bat_balls', models.IntegerField(default=0)),
                ('bat_how_out', models.CharField(default=b'DNB', max_length=32)),
                ('bat_inning_no', models.IntegerField(default=0)),
                ('bat_out_bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bat_bowler', to='cricket.Player')),
                ('bat_out_fielder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bat_fielder', to='cricket.Player')),
            ],
        ),
        migrations.CreateModel(
            name='BowlPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowl', models.BooleanField(default=False)),
                ('bowl_overs', models.FloatField(default=0)),
                ('bowl_runs', models.IntegerField(default=0)),
                ('bowl_maidens', models.IntegerField(default=0)),
                ('bowl_position', models.IntegerField(default=0)),
                ('bowl_pareconomy', models.FloatField(default=0.0)),
                ('bowl_wickets_lbw', models.IntegerField(default=0)),
                ('bowl_wickets_bowled', models.IntegerField(default=0)),
                ('bowl_wickets_stumped', models.IntegerField(default=0)),
                ('bowl_wickets_caught', models.IntegerField(default=0)),
                ('bowl_wickets_hit_wicket', models.IntegerField(default=0)),
                ('bowl_wickets_total', models.IntegerField(default=0)),
                ('bowl_inning_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FieldPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_catches', models.IntegerField(default=0)),
                ('field_run_outs', models.IntegerField(default=0)),
                ('field_stumped', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MVPPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mvp', models.BooleanField(default=False)),
                ('mvp_total', models.FloatField(default=0.0)),
                ('mvp_bat_runs', models.FloatField(default=0.0)),
                ('mvp_bat_parscorebonus', models.FloatField(default=0.0)),
                ('mvp_bowl_assisted', models.FloatField(default=0.0)),
                ('mvp_bowl_unassisted', models.FloatField(default=0.0)),
                ('mvp_bowl_economybonus', models.FloatField(default=0.0)),
                ('mvp_field_assisted', models.FloatField(default=0.0)),
                ('mvp_field_unassisted', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_club_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_club_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='competition_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='competition_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='competition_type',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ground_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ground_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_club_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_club_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.RemoveField(
            model_name='match',
            name='umpire_1_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='umpire_1_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='umpire_2_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='umpire_2_name',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bat',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bat_balls',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bat_how_out',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bat_inning_no',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bat_out_bowler',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bat_out_fielder',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bat_par_score',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bat_position',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bat_runs',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bowl',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bowl_inning_no',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bowl_maidens',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bowl_overs',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bowl_pareconomy',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bowl_position',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bowl_runs',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bowl_wickets_bowled',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bowl_wickets_caught',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bowl_wickets_hit_wicket',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bowl_wickets_lbw',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bowl_wickets_stumped',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='bowl_wickets_total',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='field_catches',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='field_run_outs',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='field_stumped',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='mvp',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='mvp_bat_parscorebonus',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='mvp_bat_runs',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='mvp_bowl_assisted',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='mvp_bowl_economybonus',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='mvp_bowl_unassisted',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='mvp_field_assisted',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='mvp_field_unassisted',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='mvp_total',
        ),
        migrations.AddField(
            model_name='pcteam',
            name='club',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cricket.Club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mvpperformance',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Match'),
        ),
        migrations.AddField(
            model_name='mvpperformance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Player'),
        ),
        migrations.AddField(
            model_name='fieldperformance',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Match'),
        ),
        migrations.AddField(
            model_name='fieldperformance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Player'),
        ),
        migrations.AddField(
            model_name='bowlperformance',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Match'),
        ),
        migrations.AddField(
            model_name='bowlperformance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Player'),
        ),
        migrations.AddField(
            model_name='batperformance',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Match'),
        ),
        migrations.AddField(
            model_name='batperformance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Player'),
        ),
    ]
