# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_auto_20181217_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationcode',
            name='user',
        ),
        migrations.DeleteModel(
            name='BattingParScores',
        ),
        migrations.RemoveField(
            model_name='playervalue',
            name='player',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='team',
        ),
        migrations.DeleteModel(
            name='ActivationCode',
        ),
        migrations.DeleteModel(
            name='PlayerValue',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamPlayer',
        ),
    ]
