# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0005_auto_20181218_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='inning',
            name='inning_no',
            field=models.IntegerField(default=0),
        ),
    ]
