# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0007_auto_20190110_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScorerAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Match')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Scorer')),
            ],
        ),
    ]
