# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0008_scorer_scorerassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='fk_away_team',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='fk_competition',
            new_name='competition',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='fk_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='fk_ground',
            new_name='ground',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='fk_home_team',
            new_name='home_team',
        ),
    ]
