# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-27 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190110_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='home_club',
            field=models.BooleanField(default=False),
        ),
    ]
