# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190127_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inning',
            name='bat_team_id',
        ),
        migrations.RemoveField(
            model_name='inning',
            name='bowl_team_id',
        ),
        migrations.AddField(
            model_name='inning',
            name='bat_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bat_team', to='core.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inning',
            name='bowl_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bowl_team', to='core.Team'),
            preserve_default=False,
        ),
    ]
